[project]
name = "portfolio-project-1"
version = "0.1.0"
description = "Revenue Leakage Recovery Pipeline"
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "dbt-core>=1.11.4",
    "dbt-duckdb>=1.10.0",
    "faker>=40.4.0",
]
